#!/bin/bash

echo "Navigating to /home/csgo-src/src..."
cd /root/csgo_test/src || exit 1

# Clean up old logs folder
echo "Removing existing logs directory..."
rm -rf ./logs

echo "Cleaning previous build artifacts..."
find . -type f \( -name "*.o" -o -name "*.a" -o -name "*.so" -o -name "*.d" -o -name "*.lo" \) -delete
find . -type d \( -name ".libs" -o -name "Release" -o -name "Debug" \) -exec rm -rf {} +

echo "Clean finished."